AWSTemplateFormatVersion: '2010-09-09'

Description: Account access management for IAM users

Resources:
  RequireMFAManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Denies access to all AWS actions except those necessary to authenticate using MFA
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowListActions
            Effect: Allow
            Action:
              - iam:ListUsers
              - iam:ListVirtualMFADevices
            Resource: '*'
          - Sid: AllowUserToCreateVirtualMFADevice
            Effect: Allow
            Action:
              - iam:CreateVirtualMFADevice
            Resource: arn:aws:iam::*:mfa/*
          - Sid: AllowUserToManageTheirOwnMFA
            Effect: Allow
            Action:
              - iam:EnableMFADevice
              - iam:ListMFADevices
              - iam:ResyncMFADevice
            Resource: arn:aws:iam::*:user/${aws:username}
          - Sid: AllowUserToDeactivateTheirOwnMFAOnlyWhenUsingMFA
            Effect: Allow
            Action:
              - iam:DeactivateMFADevice
            Resource:
              - arn:aws:iam::*:user/${aws:username}
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: 'true'
          - Sid: BlockMostAccessUnlessSignedInWithMFA
            Effect: Deny
            NotAction:
              - iam:CreateVirtualMFADevice
              - iam:EnableMFADevice
              - iam:ListMFADevices
              - iam:ListUsers
              - iam:ListVirtualMFADevices
              - iam:ResyncMFADevice
              - sts:GetSessionToken
              - codecommit:GitPull
              - codecommit:GitPush
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt
              - kms:GenerateDataKey
              - kms:GenerateDataKeyWithoutPlaintext
              - kms:DescribeKey
            Resource: '*'
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: 'false'
  AdminsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Admins
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
        - !Ref RequireMFAManagedPolicy
