AWSTemplateFormatVersion: "2010-09-09"

Description: Laravel Lambda S3 Buckets

Parameters:
  DomainName:
    Description: The domain name
    Type: String
  CloudFrontDistributionId:
    Description: ID of the CloudFront distribution
    Default: unused
    Type: String
Conditions:
  CloudFrontDistributionIdExists: !Not
    - !Equals
      - !Ref CloudFrontDistributionId
      - unused

Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub ${DomainName}-assets
      LifecycleConfiguration:
        Rules:
          - NoncurrentVersionExpiration:
              NoncurrentDays: 30
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
  AssetsBucketPolicy:
    Condition: CloudFrontDistributionIdExists
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontGetRequests
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${AssetsBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistributionId}
  CICDArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub ${DomainName}-cicd-artifacts
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub ${DomainName}-config
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - NoncurrentVersionExpiration:
              NoncurrentDays: 30
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
  InternalBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub ${DomainName}-internal
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - NoncurrentVersionExpiration:
              NoncurrentDays: 30
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

Outputs:
  AssetsBucketName:
    Description: The assets bucket name
    Export:
      Name: !Sub ${AWS::StackName}-AssetsBucketName
    Value: !Ref AssetsBucket
  AssetsBucketARN:
    Description: The assets bucket ARN
    Export:
      Name: !Sub ${AWS::StackName}-AssetsBucketARN
    Value: !GetAtt AssetsBucket.Arn
  AssetsBucketRegionalDomainName:
    Description: The assets bucket regional domain name
    Export:
      Name: !Sub ${AWS::StackName}-AssetsBucketRegionalDomainName
    Value: !GetAtt AssetsBucket.RegionalDomainName
  CICDArtifactsBucketName:
    Description: The CI/CD artifacts bucket name
    Export:
      Name: !Sub ${AWS::StackName}-CICDArtifactsBucketName
    Value: !Ref CICDArtifactsBucket
  CICDArtifactsBucketARN:
    Description: The CI/CD artifacts bucket ARN
    Export:
      Name: !Sub ${AWS::StackName}-CICDArtifactsBucketARN
    Value: !GetAtt CICDArtifactsBucket.Arn
  ConfigBucketName:
    Description: The config bucket name
    Export:
      Name: !Sub ${AWS::StackName}-ConfigBucketName
    Value: !Ref ConfigBucket
  ConfigBucketARN:
    Description: The config bucket ARN
    Export:
      Name: !Sub ${AWS::StackName}-ConfigBucketARN
    Value: !GetAtt ConfigBucket.Arn
  InternalBucketName:
    Description: The internal bucket name
    Export:
      Name: !Sub ${AWS::StackName}-InternalBucketName
    Value: !Ref InternalBucket
  InternalBucketARN:
    Description: The internal bucket ARN
    Export:
      Name: !Sub ${AWS::StackName}-InternalBucketARN
    Value: !GetAtt InternalBucket.Arn
