AWSTemplateFormatVersion: "2010-09-09"

Description: Laravel Lambda DynamoDB Table

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

Outputs:
  TableName:
    Description: The DynamoDB table name
    Export:
      Name: !Sub ${AWS::StackName}-TableName
    Value: !Ref Table
  TableARN:
    Description: The DynamoDB table ARN
    Export:
      Name: !Sub ${AWS::StackName}-TableARN
    Value: !GetAtt Table.Arn
