AWSTemplateFormatVersion: "2010-09-09"

Description: Laravel Lambda HTTP Lambda Function

Parameters:
  LambdaSecurityGroupID:
    Description: ID of the DB Lambda Security Group
    Type: AWS::EC2::SecurityGroup::Id
  Environment:
    Description: Deployment environment
    AllowedValues:
      - test
      - live
    Type: String
  LogRetention:
    Default: 90
    Description: Number of days to keep the logs
    AllowedValues:
      [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 182, 3653]
    Type: Number
  Memory:
    Default: 1024
    Description: Memory allocation
    Type: Number
  RoleARN:
    Description: ARN of the Lambda role
    Type: String
  Timeout:
    Default: 10
    Description: The maximum function execution time (in seconds)
    Type: Number

Resources:
  Alias:
    Type: AWS::Lambda::Alias
    Properties:
      Description: !Sub ${Environment} alias
      FunctionName: !Ref Function
      FunctionVersion: $LATEST
      Name: !Ref Environment
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Code:
        ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/core-placeholder:latest
      Description: Laravel Lambda HTTP Lambda Function
      MemorySize: !Ref Memory
      PackageType: Image
      Role: !Ref RoleARN
      Timeout: !Ref Timeout
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupID
        SubnetIds:
          - !ImportValue core-network-PrivateSubnet1
          - !ImportValue core-network-PrivateSubnet2
          - !ImportValue core-network-PrivateSubnet3
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Function}
      RetentionInDays: !Ref LogRetention
  URL:
    Type: AWS::Lambda::Url
    DependsOn: Function
    Properties:
      AuthType: AWS_IAM
      InvokeMode: BUFFERED
      Qualifier: !Ref Environment
      TargetFunctionArn: !GetAtt Function.Arn

Outputs:
  AliasARN:
    Description: The alias
    Export:
      Name: !Sub ${AWS::StackName}-AliasARN
    Value: !GetAtt Alias.AliasArn
  FunctionURL:
    Description: The function URL
    Export:
      Name: !Sub ${AWS::StackName}-FunctionURL
    Value: !GetAtt URL.FunctionUrl
